version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nextjs-portfolio-ts # コンテナ名を変更 (任意)
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    # ホットリロードがうまく動かない場合に試すオプション (特にWindows)
    # watch:
    #   - action: sync
    #     path: .
    #     target: /app
    #     ignore:
    #       - node_modules/
    #       - .next/